# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/Vivado/PREPROCESSTEST-basebroadOK/PREPROCESSTEST-basebroadOK.srcs/sources_1/bd/design_1/ip/design_1_axis_subset_converter_4_0/design_1_axis_subset_converter_4_0.xci
# IP: The module: 'design_1_axis_subset_converter_4_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Vivado/PREPROCESSTEST-basebroadOK/PREPROCESSTEST-basebroadOK.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_4_0/design_1_axis_subset_converter_4_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_subset_converter_4_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: h:/Vivado/PREPROCESSTEST-basebroadOK/PREPROCESSTEST-basebroadOK.srcs/sources_1/bd/design_1/ip/design_1_axis_subset_converter_4_0/design_1_axis_subset_converter_4_0.xci
# IP: The module: 'design_1_axis_subset_converter_4_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Vivado/PREPROCESSTEST-basebroadOK/PREPROCESSTEST-basebroadOK.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_4_0/design_1_axis_subset_converter_4_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_subset_converter_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
