// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Block_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        xleft_s_dout,
        xleft_s_empty_n,
        xleft_s_read,
        ch2x_out_out_din,
        ch2x_out_out_full_n,
        ch2x_out_out_write,
        ch3x_out_out_din,
        ch3x_out_out_full_n,
        ch3x_out_out_write,
        ch4x_out_out_din,
        ch4x_out_out_full_n,
        ch4x_out_out_write,
        ch5x_out_out_din,
        ch5x_out_out_full_n,
        ch5x_out_out_write,
        ch6x_out_out_din,
        ch6x_out_out_full_n,
        ch6x_out_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] xleft_s_dout;
input   xleft_s_empty_n;
output   xleft_s_read;
output  [15:0] ch2x_out_out_din;
input   ch2x_out_out_full_n;
output   ch2x_out_out_write;
output  [15:0] ch3x_out_out_din;
input   ch3x_out_out_full_n;
output   ch3x_out_out_write;
output  [15:0] ch4x_out_out_din;
input   ch4x_out_out_full_n;
output   ch4x_out_out_write;
output  [15:0] ch5x_out_out_din;
input   ch5x_out_out_full_n;
output   ch5x_out_out_write;
output  [15:0] ch6x_out_out_din;
input   ch6x_out_out_full_n;
output   ch6x_out_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg xleft_s_read;
reg ch2x_out_out_write;
reg ch3x_out_out_write;
reg ch4x_out_out_write;
reg ch5x_out_out_write;
reg ch6x_out_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    xleft_s_blk_n;
reg    ch2x_out_out_blk_n;
reg    ch3x_out_out_blk_n;
reg    ch4x_out_out_blk_n;
reg    ch5x_out_out_blk_n;
reg    ch6x_out_out_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ch6x_out_out_full_n == 1'b0) | (ch5x_out_out_full_n == 1'b0) | (ch4x_out_out_full_n == 1'b0) | (ch3x_out_out_full_n == 1'b0) | (ch2x_out_out_full_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ch6x_out_out_full_n == 1'b0) | (ch5x_out_out_full_n == 1'b0) | (ch4x_out_out_full_n == 1'b0) | (ch3x_out_out_full_n == 1'b0) | (ch2x_out_out_full_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ch6x_out_out_full_n == 1'b0) | (ch5x_out_out_full_n == 1'b0) | (ch4x_out_out_full_n == 1'b0) | (ch3x_out_out_full_n == 1'b0) | (ch2x_out_out_full_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ch2x_out_out_blk_n = ch2x_out_out_full_n;
    end else begin
        ch2x_out_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ch6x_out_out_full_n == 1'b0) | (ch5x_out_out_full_n == 1'b0) | (ch4x_out_out_full_n == 1'b0) | (ch3x_out_out_full_n == 1'b0) | (ch2x_out_out_full_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ch2x_out_out_write = 1'b1;
    end else begin
        ch2x_out_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ch3x_out_out_blk_n = ch3x_out_out_full_n;
    end else begin
        ch3x_out_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ch6x_out_out_full_n == 1'b0) | (ch5x_out_out_full_n == 1'b0) | (ch4x_out_out_full_n == 1'b0) | (ch3x_out_out_full_n == 1'b0) | (ch2x_out_out_full_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ch3x_out_out_write = 1'b1;
    end else begin
        ch3x_out_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ch4x_out_out_blk_n = ch4x_out_out_full_n;
    end else begin
        ch4x_out_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ch6x_out_out_full_n == 1'b0) | (ch5x_out_out_full_n == 1'b0) | (ch4x_out_out_full_n == 1'b0) | (ch3x_out_out_full_n == 1'b0) | (ch2x_out_out_full_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ch4x_out_out_write = 1'b1;
    end else begin
        ch4x_out_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ch5x_out_out_blk_n = ch5x_out_out_full_n;
    end else begin
        ch5x_out_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ch6x_out_out_full_n == 1'b0) | (ch5x_out_out_full_n == 1'b0) | (ch4x_out_out_full_n == 1'b0) | (ch3x_out_out_full_n == 1'b0) | (ch2x_out_out_full_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ch5x_out_out_write = 1'b1;
    end else begin
        ch5x_out_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ch6x_out_out_blk_n = ch6x_out_out_full_n;
    end else begin
        ch6x_out_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ch6x_out_out_full_n == 1'b0) | (ch5x_out_out_full_n == 1'b0) | (ch4x_out_out_full_n == 1'b0) | (ch3x_out_out_full_n == 1'b0) | (ch2x_out_out_full_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ch6x_out_out_write = 1'b1;
    end else begin
        ch6x_out_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        xleft_s_blk_n = xleft_s_empty_n;
    end else begin
        xleft_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ch6x_out_out_full_n == 1'b0) | (ch5x_out_out_full_n == 1'b0) | (ch4x_out_out_full_n == 1'b0) | (ch3x_out_out_full_n == 1'b0) | (ch2x_out_out_full_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        xleft_s_read = 1'b1;
    end else begin
        xleft_s_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ch6x_out_out_full_n == 1'b0) | (ch5x_out_out_full_n == 1'b0) | (ch4x_out_out_full_n == 1'b0) | (ch3x_out_out_full_n == 1'b0) | (ch2x_out_out_full_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ch2x_out_out_din = (xleft_s_dout + 16'd32);

assign ch3x_out_out_din = (xleft_s_dout + 16'd64);

assign ch4x_out_out_din = (xleft_s_dout + 16'd96);

assign ch5x_out_out_din = (xleft_s_dout + 16'd128);

assign ch6x_out_out_din = (xleft_s_dout + 16'd160);

endmodule //Block_proc
