# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/Vivado/camerasignaltest/camerasignaltest.srcs/sources_1/bd/design_1/ip/design_1_axis_subset_converter_2_1/design_1_axis_subset_converter_2_1.xci
# IP: The module: 'design_1_axis_subset_converter_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Vivado/camerasignaltest/camerasignaltest.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_2_1/design_1_axis_subset_converter_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_subset_converter_2_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: H:/Vivado/camerasignaltest/camerasignaltest.srcs/sources_1/bd/design_1/ip/design_1_axis_subset_converter_2_1/design_1_axis_subset_converter_2_1.xci
# IP: The module: 'design_1_axis_subset_converter_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Vivado/camerasignaltest/camerasignaltest.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_2_1/design_1_axis_subset_converter_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_subset_converter_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
