-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Add_Char6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    src_data_stream_0_V_empty_n : IN STD_LOGIC;
    src_data_stream_0_V_read : OUT STD_LOGIC;
    src_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    src_data_stream_1_V_empty_n : IN STD_LOGIC;
    src_data_stream_1_V_read : OUT STD_LOGIC;
    src_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    src_data_stream_2_V_empty_n : IN STD_LOGIC;
    src_data_stream_2_V_read : OUT STD_LOGIC;
    src_data_stream_3_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    src_data_stream_3_V_empty_n : IN STD_LOGIC;
    src_data_stream_3_V_read : OUT STD_LOGIC;
    dst_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_data_stream_0_V_full_n : IN STD_LOGIC;
    dst_data_stream_0_V_write : OUT STD_LOGIC;
    dst_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_data_stream_1_V_full_n : IN STD_LOGIC;
    dst_data_stream_1_V_write : OUT STD_LOGIC;
    dst_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_data_stream_2_V_full_n : IN STD_LOGIC;
    dst_data_stream_2_V_write : OUT STD_LOGIC;
    dst_data_stream_3_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_data_stream_3_V_full_n : IN STD_LOGIC;
    dst_data_stream_3_V_write : OUT STD_LOGIC;
    ch6x_loc_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    ch6x_loc_empty_n : IN STD_LOGIC;
    ch6x_loc_read : OUT STD_LOGIC;
    ytop_s_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    ytop_s_empty_n : IN STD_LOGIC;
    ytop_s_read : OUT STD_LOGIC;
    char6_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    char6_empty_n : IN STD_LOGIC;
    char6_read : OUT STD_LOGIC;
    color1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    color1_empty_n : IN STD_LOGIC;
    color1_read : OUT STD_LOGIC;
    color2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    color2_empty_n : IN STD_LOGIC;
    color2_read : OUT STD_LOGIC;
    color3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    color3_empty_n : IN STD_LOGIC;
    color3_read : OUT STD_LOGIC );
end;


architecture behav of Add_Char6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv8_1A : STD_LOGIC_VECTOR (7 downto 0) := "00011010";
    constant ap_const_lv17_40 : STD_LOGIC_VECTOR (16 downto 0) := "00000000001000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv17_20 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000100000";
    constant ap_const_lv10_2D0 : STD_LOGIC_VECTOR (9 downto 0) := "1011010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_500 : STD_LOGIC_VECTOR (10 downto 0) := "10100000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal letter298_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal letter298_ce0 : STD_LOGIC;
    signal letter298_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal src_data_stream_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_36_i_i_reg_723 : STD_LOGIC_VECTOR (0 downto 0);
    signal src_data_stream_1_V_blk_n : STD_LOGIC;
    signal src_data_stream_2_V_blk_n : STD_LOGIC;
    signal src_data_stream_3_V_blk_n : STD_LOGIC;
    signal dst_data_stream_0_V_blk_n : STD_LOGIC;
    signal dst_data_stream_1_V_blk_n : STD_LOGIC;
    signal dst_data_stream_2_V_blk_n : STD_LOGIC;
    signal dst_data_stream_3_V_blk_n : STD_LOGIC;
    signal ch6x_loc_blk_n : STD_LOGIC;
    signal ytop_s_blk_n : STD_LOGIC;
    signal char6_blk_n : STD_LOGIC;
    signal color1_blk_n : STD_LOGIC;
    signal color2_blk_n : STD_LOGIC;
    signal color3_blk_n : STD_LOGIC;
    signal j_i_i_reg_395 : STD_LOGIC_VECTOR (10 downto 0);
    signal ytop_read_reg_649 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal markpix_val_0_reg_654 : STD_LOGIC_VECTOR (7 downto 0);
    signal markpix_val_1_reg_659 : STD_LOGIC_VECTOR (7 downto 0);
    signal markpix_val_2_reg_664 : STD_LOGIC_VECTOR (7 downto 0);
    signal ch6x_loc_read_reg_669 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_i_reg_675 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_cast_i_i_fu_412_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_cast_i_i_reg_680 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_25_i_i_fu_416_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_25_i_i_reg_685 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_13_cast_fu_426_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_13_cast_reg_690 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_28_i_i_fu_438_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_28_i_i_reg_695 : STD_LOGIC_VECTOR (16 downto 0);
    signal i_fu_454_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_reg_703 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_29_i_i_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_reg_713 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_reg_718 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_36_i_i_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state4_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal j_fu_532_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_20_fu_581_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_reg_732 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_reg_739 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state4 : STD_LOGIC;
    signal i_i_i_reg_384 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_14_cast_fu_489_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_fu_422_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_27_cast108_i_i_fu_434_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal i_cast107_i_i_fu_444_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_32_cast_i_i_fu_465_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_33_i_i_fu_469_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_35_i_i_cast_fu_474_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_484_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ult_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev8_fu_499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp15_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_i_i_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_demorgan_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_cast106_i_i_fu_522_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ult9_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_cast_i_i_fu_549_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_42_i_i_fu_558_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_563_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal xos_fu_573_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal bvh_d_index_fu_577_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_41_i_i_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp16_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal markpix_val_0_1_fu_599_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal markpix_val_1_1_fu_605_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal markpix_val_2_1_fu_611_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component Add_Char1_letter IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    letter298_U : component Add_Char1_letter
    generic map (
        DataWidth => 16,
        AddressRange => 864,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => letter298_address0,
        ce0 => letter298_ce0,
        q0 => letter298_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_29_i_i_fu_448_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state4);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_i_i_reg_384_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_i_i_reg_384 <= i_reg_703;
            elsif ((not(((color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (ch6x_loc_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_i_i_reg_384 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    j_i_i_reg_395_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_fu_526_p2 = ap_const_lv1_0))) then 
                j_i_i_reg_395 <= j_fu_532_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                j_i_i_reg_395 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (ch6x_loc_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                ch6x_loc_read_reg_669 <= ch6x_loc_dout;
                markpix_val_0_reg_654 <= color1_dout;
                markpix_val_1_reg_659 <= color2_dout;
                markpix_val_2_reg_664 <= color3_dout;
                    tmp_13_cast_reg_690(10 downto 5) <= tmp_13_cast_fu_426_p3(10 downto 5);
                tmp_25_i_i_reg_685 <= tmp_25_i_i_fu_416_p2;
                tmp_28_i_i_reg_695 <= tmp_28_i_i_fu_438_p2;
                    tmp_cast_i_i_reg_680(15 downto 0) <= tmp_cast_i_i_fu_412_p1(15 downto 0);
                tmp_i_i_reg_675 <= tmp_i_i_fu_406_p2;
                ytop_read_reg_649 <= ytop_s_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_703 <= i_fu_454_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                p_Val2_s_reg_718 <= letter298_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_29_i_i_fu_448_p2 = ap_const_lv1_0))) then
                sel_tmp6_reg_713 <= sel_tmp6_fu_516_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_fu_526_p2 = ap_const_lv1_0))) then
                sel_tmp7_reg_739 <= sel_tmp7_fu_593_p2;
                tmp_20_reg_732 <= tmp_20_fu_581_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_36_i_i_reg_723 <= tmp_36_i_i_fu_526_p2;
            end if;
        end if;
    end process;
    tmp_cast_i_i_reg_680(16) <= '0';
    tmp_13_cast_reg_690(4 downto 0) <= "00000";

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ch6x_loc_empty_n, ytop_s_empty_n, char6_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, ap_CS_fsm_state2, tmp_29_i_i_fu_448_p2, tmp_36_i_i_fu_526_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (ch6x_loc_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_29_i_i_fu_448_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (tmp_36_i_i_fu_526_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (tmp_36_i_i_fu_526_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state6 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(src_data_stream_0_V_empty_n, src_data_stream_1_V_empty_n, src_data_stream_2_V_empty_n, src_data_stream_3_V_empty_n, dst_data_stream_0_V_full_n, dst_data_stream_1_V_full_n, dst_data_stream_2_V_full_n, dst_data_stream_3_V_full_n, ap_enable_reg_pp0_iter1, tmp_36_i_i_reg_723)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((dst_data_stream_3_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((dst_data_stream_2_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((dst_data_stream_1_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((dst_data_stream_0_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_3_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_2_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_1_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_0_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(src_data_stream_0_V_empty_n, src_data_stream_1_V_empty_n, src_data_stream_2_V_empty_n, src_data_stream_3_V_empty_n, dst_data_stream_0_V_full_n, dst_data_stream_1_V_full_n, dst_data_stream_2_V_full_n, dst_data_stream_3_V_full_n, ap_enable_reg_pp0_iter1, tmp_36_i_i_reg_723)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((dst_data_stream_3_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((dst_data_stream_2_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((dst_data_stream_1_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((dst_data_stream_0_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_3_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_2_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_1_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_0_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(src_data_stream_0_V_empty_n, src_data_stream_1_V_empty_n, src_data_stream_2_V_empty_n, src_data_stream_3_V_empty_n, dst_data_stream_0_V_full_n, dst_data_stream_1_V_full_n, dst_data_stream_2_V_full_n, dst_data_stream_3_V_full_n, ap_enable_reg_pp0_iter1, tmp_36_i_i_reg_723)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((dst_data_stream_3_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((dst_data_stream_2_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((dst_data_stream_1_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((dst_data_stream_0_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_3_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_2_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_1_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_0_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0))));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, ch6x_loc_empty_n, ytop_s_empty_n, char6_empty_n, color1_empty_n, color2_empty_n, color3_empty_n)
    begin
                ap_block_state1 <= ((color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (ch6x_loc_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state4_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter1_assign_proc : process(src_data_stream_0_V_empty_n, src_data_stream_1_V_empty_n, src_data_stream_2_V_empty_n, src_data_stream_3_V_empty_n, dst_data_stream_0_V_full_n, dst_data_stream_1_V_full_n, dst_data_stream_2_V_full_n, dst_data_stream_3_V_full_n, tmp_36_i_i_reg_723)
    begin
                ap_block_state5_pp0_stage0_iter1 <= (((dst_data_stream_3_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((dst_data_stream_2_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((dst_data_stream_1_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((dst_data_stream_0_V_full_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_3_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_2_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_1_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)) or ((src_data_stream_0_V_empty_n = ap_const_logic_0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0)));
    end process;


    ap_condition_pp0_exit_iter0_state4_assign_proc : process(tmp_36_i_i_fu_526_p2)
    begin
        if ((tmp_36_i_i_fu_526_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, tmp_29_i_i_fu_448_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_29_i_i_fu_448_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    bvh_d_index_fu_577_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xos_fu_573_p1),32));

    ch6x_loc_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ch6x_loc_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ch6x_loc_blk_n <= ch6x_loc_empty_n;
        else 
            ch6x_loc_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ch6x_loc_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ch6x_loc_empty_n, ytop_s_empty_n, char6_empty_n, color1_empty_n, color2_empty_n, color3_empty_n)
    begin
        if ((not(((color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (ch6x_loc_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ch6x_loc_read <= ap_const_logic_1;
        else 
            ch6x_loc_read <= ap_const_logic_0;
        end if; 
    end process;


    char6_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char6_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char6_blk_n <= char6_empty_n;
        else 
            char6_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    char6_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ch6x_loc_empty_n, ytop_s_empty_n, char6_empty_n, color1_empty_n, color2_empty_n, color3_empty_n)
    begin
        if ((not(((color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (ch6x_loc_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char6_read <= ap_const_logic_1;
        else 
            char6_read <= ap_const_logic_0;
        end if; 
    end process;


    color1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, color1_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color1_blk_n <= color1_empty_n;
        else 
            color1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    color1_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ch6x_loc_empty_n, ytop_s_empty_n, char6_empty_n, color1_empty_n, color2_empty_n, color3_empty_n)
    begin
        if ((not(((color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (ch6x_loc_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color1_read <= ap_const_logic_1;
        else 
            color1_read <= ap_const_logic_0;
        end if; 
    end process;


    color2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, color2_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color2_blk_n <= color2_empty_n;
        else 
            color2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    color2_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ch6x_loc_empty_n, ytop_s_empty_n, char6_empty_n, color1_empty_n, color2_empty_n, color3_empty_n)
    begin
        if ((not(((color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (ch6x_loc_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color2_read <= ap_const_logic_1;
        else 
            color2_read <= ap_const_logic_0;
        end if; 
    end process;


    color3_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, color3_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color3_blk_n <= color3_empty_n;
        else 
            color3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    color3_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ch6x_loc_empty_n, ytop_s_empty_n, char6_empty_n, color1_empty_n, color2_empty_n, color3_empty_n)
    begin
        if ((not(((color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (ch6x_loc_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color3_read <= ap_const_logic_1;
        else 
            color3_read <= ap_const_logic_0;
        end if; 
    end process;


    dst_data_stream_0_V_blk_n_assign_proc : process(dst_data_stream_0_V_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_36_i_i_reg_723)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            dst_data_stream_0_V_blk_n <= dst_data_stream_0_V_full_n;
        else 
            dst_data_stream_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dst_data_stream_0_V_din <= 
        markpix_val_0_1_fu_599_p3 when (sel_tmp7_reg_739(0) = '1') else 
        src_data_stream_0_V_dout;

    dst_data_stream_0_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_36_i_i_reg_723, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0))) then 
            dst_data_stream_0_V_write <= ap_const_logic_1;
        else 
            dst_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    dst_data_stream_1_V_blk_n_assign_proc : process(dst_data_stream_1_V_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_36_i_i_reg_723)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            dst_data_stream_1_V_blk_n <= dst_data_stream_1_V_full_n;
        else 
            dst_data_stream_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dst_data_stream_1_V_din <= 
        markpix_val_1_1_fu_605_p3 when (sel_tmp7_reg_739(0) = '1') else 
        src_data_stream_1_V_dout;

    dst_data_stream_1_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_36_i_i_reg_723, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0))) then 
            dst_data_stream_1_V_write <= ap_const_logic_1;
        else 
            dst_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    dst_data_stream_2_V_blk_n_assign_proc : process(dst_data_stream_2_V_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_36_i_i_reg_723)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            dst_data_stream_2_V_blk_n <= dst_data_stream_2_V_full_n;
        else 
            dst_data_stream_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dst_data_stream_2_V_din <= 
        markpix_val_2_1_fu_611_p3 when (sel_tmp7_reg_739(0) = '1') else 
        src_data_stream_2_V_dout;

    dst_data_stream_2_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_36_i_i_reg_723, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0))) then 
            dst_data_stream_2_V_write <= ap_const_logic_1;
        else 
            dst_data_stream_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    dst_data_stream_3_V_blk_n_assign_proc : process(dst_data_stream_3_V_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_36_i_i_reg_723)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            dst_data_stream_3_V_blk_n <= dst_data_stream_3_V_full_n;
        else 
            dst_data_stream_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dst_data_stream_3_V_din <= 
        ap_const_lv8_0 when (sel_tmp7_reg_739(0) = '1') else 
        src_data_stream_3_V_dout;

    dst_data_stream_3_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_36_i_i_reg_723, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0))) then 
            dst_data_stream_3_V_write <= ap_const_logic_1;
        else 
            dst_data_stream_3_V_write <= ap_const_logic_0;
        end if; 
    end process;

    i_cast107_i_i_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_i_i_reg_384),16));
    i_fu_454_p2 <= std_logic_vector(unsigned(i_i_i_reg_384) + unsigned(ap_const_lv10_1));

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, tmp_29_i_i_fu_448_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_29_i_i_fu_448_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    j_cast106_i_i_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_i_i_reg_395),16));
    j_fu_532_p2 <= std_logic_vector(unsigned(j_i_i_reg_395) + unsigned(ap_const_lv11_1));
    letter298_address0 <= tmp_14_cast_fu_489_p1(10 - 1 downto 0);

    letter298_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            letter298_ce0 <= ap_const_logic_1;
        else 
            letter298_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    markpix_val_0_1_fu_599_p3 <= 
        markpix_val_0_reg_654 when (tmp_20_reg_732(0) = '1') else 
        ap_const_lv8_FF;
    markpix_val_1_1_fu_605_p3 <= 
        markpix_val_1_reg_659 when (tmp_20_reg_732(0) = '1') else 
        ap_const_lv8_FF;
    markpix_val_2_1_fu_611_p3 <= 
        markpix_val_2_reg_664 when (tmp_20_reg_732(0) = '1') else 
        ap_const_lv8_FF;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    rev8_fu_499_p2 <= (ult_fu_494_p2 xor ap_const_lv1_1);
    rev_fu_543_p2 <= (ult9_fu_538_p2 xor ap_const_lv1_1);
    sel_tmp6_demorgan_fu_510_p2 <= (tmp_31_i_i_fu_460_p2 or tmp15_fu_505_p2);
    sel_tmp6_fu_516_p2 <= (sel_tmp6_demorgan_fu_510_p2 xor ap_const_lv1_1);
    sel_tmp7_fu_593_p2 <= (tmp16_fu_588_p2 and rev_fu_543_p2);

    src_data_stream_0_V_blk_n_assign_proc : process(src_data_stream_0_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_36_i_i_reg_723)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            src_data_stream_0_V_blk_n <= src_data_stream_0_V_empty_n;
        else 
            src_data_stream_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    src_data_stream_0_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_36_i_i_reg_723, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0))) then 
            src_data_stream_0_V_read <= ap_const_logic_1;
        else 
            src_data_stream_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    src_data_stream_1_V_blk_n_assign_proc : process(src_data_stream_1_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_36_i_i_reg_723)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            src_data_stream_1_V_blk_n <= src_data_stream_1_V_empty_n;
        else 
            src_data_stream_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    src_data_stream_1_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_36_i_i_reg_723, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0))) then 
            src_data_stream_1_V_read <= ap_const_logic_1;
        else 
            src_data_stream_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    src_data_stream_2_V_blk_n_assign_proc : process(src_data_stream_2_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_36_i_i_reg_723)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            src_data_stream_2_V_blk_n <= src_data_stream_2_V_empty_n;
        else 
            src_data_stream_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    src_data_stream_2_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_36_i_i_reg_723, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0))) then 
            src_data_stream_2_V_read <= ap_const_logic_1;
        else 
            src_data_stream_2_V_read <= ap_const_logic_0;
        end if; 
    end process;


    src_data_stream_3_V_blk_n_assign_proc : process(src_data_stream_3_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_36_i_i_reg_723)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            src_data_stream_3_V_blk_n <= src_data_stream_3_V_empty_n;
        else 
            src_data_stream_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    src_data_stream_3_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_36_i_i_reg_723, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_36_i_i_reg_723 = ap_const_lv1_0))) then 
            src_data_stream_3_V_read <= ap_const_logic_1;
        else 
            src_data_stream_3_V_read <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp15_fu_505_p2 <= (tmp_i_i_reg_675 or rev8_fu_499_p2);
    tmp16_fu_588_p2 <= (tmp_41_i_i_fu_553_p2 and sel_tmp6_reg_713);
    tmp_13_cast_fu_426_p3 <= (tmp_fu_422_p1 & ap_const_lv5_0);
    tmp_14_cast_fu_489_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_484_p2),64));
    tmp_20_fu_581_p3 <= p_Val2_s_reg_718(to_integer(unsigned(bvh_d_index_fu_577_p1)) downto to_integer(unsigned(bvh_d_index_fu_577_p1))) when (to_integer(unsigned(bvh_d_index_fu_577_p1))>= 0 and to_integer(unsigned(bvh_d_index_fu_577_p1))<=15) else "-";
    tmp_25_i_i_fu_416_p2 <= std_logic_vector(unsigned(ap_const_lv17_40) + unsigned(tmp_cast_i_i_fu_412_p1));
    tmp_27_cast108_i_i_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ch6x_loc_dout),17));
    tmp_28_i_i_fu_438_p2 <= std_logic_vector(unsigned(ap_const_lv17_20) + unsigned(tmp_27_cast108_i_i_fu_434_p1));
    tmp_29_i_i_fu_448_p2 <= "1" when (i_i_i_reg_384 = ap_const_lv10_2D0) else "0";
    tmp_31_i_i_fu_460_p2 <= "1" when (unsigned(i_cast107_i_i_fu_444_p1) < unsigned(ytop_read_reg_649)) else "0";
    tmp_32_cast_i_i_fu_465_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_i_i_reg_384),17));
    tmp_33_i_i_fu_469_p2 <= std_logic_vector(unsigned(tmp_32_cast_i_i_fu_465_p1) - unsigned(tmp_cast_i_i_reg_680));
    tmp_35_i_i_cast_fu_474_p4 <= tmp_33_i_i_fu_469_p2(11 downto 1);
    tmp_36_i_i_fu_526_p2 <= "1" when (j_i_i_reg_395 = ap_const_lv11_500) else "0";
    tmp_40_cast_i_i_fu_549_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_i_i_reg_395),17));
    tmp_41_i_i_fu_553_p2 <= "1" when (unsigned(tmp_40_cast_i_i_fu_549_p1) < unsigned(tmp_28_i_i_reg_695)) else "0";
    tmp_42_i_i_fu_558_p2 <= std_logic_vector(unsigned(j_cast106_i_i_fu_522_p1) - unsigned(ch6x_loc_read_reg_669));
    tmp_5_fu_484_p2 <= std_logic_vector(unsigned(tmp_13_cast_reg_690) + unsigned(tmp_35_i_i_cast_fu_474_p4));
    tmp_cast_i_i_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ytop_s_dout),17));
    tmp_fu_422_p1 <= char6_dout(6 - 1 downto 0);
    tmp_i_i_fu_406_p2 <= "1" when (char6_dout = ap_const_lv8_1A) else "0";
    tmp_s_fu_563_p4 <= tmp_42_i_i_fu_558_p2(15 downto 1);
    ult9_fu_538_p2 <= "1" when (unsigned(j_cast106_i_i_fu_522_p1) < unsigned(ch6x_loc_read_reg_669)) else "0";
    ult_fu_494_p2 <= "1" when (unsigned(tmp_32_cast_i_i_fu_465_p1) < unsigned(tmp_25_i_i_reg_685)) else "0";
        xos_fu_573_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_fu_563_p4),16));


    ytop_s_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ytop_s_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ytop_s_blk_n <= ytop_s_empty_n;
        else 
            ytop_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ytop_s_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ch6x_loc_empty_n, ytop_s_empty_n, char6_empty_n, color1_empty_n, color2_empty_n, color3_empty_n)
    begin
        if ((not(((color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (ch6x_loc_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ytop_s_read <= ap_const_logic_1;
        else 
            ytop_s_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
